"""added relationship between bike and cyclist

Revision ID: 12535c01a3ec
Revises: 8ac1f0fa94f9
Create Date: 2022-11-07 11:13:59.035129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12535c01a3ec'
down_revision = '8ac1f0fa94f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('cyclist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bike', 'cyclist', ['cyclist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bike', type_='foreignkey')
    op.drop_column('bike', 'cyclist_id')
    # ### end Alembic commands ###
